# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/rsa.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(970, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.txtplaintext = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txtplaintext.setGeometry(QtCore.QRect(140, 160, 281, 71))
        self.txtplaintext.setObjectName("txtplaintext")
        self.txtciphertext = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txtciphertext.setGeometry(QtCore.QRect(140, 260, 281, 71))
        self.txtciphertext.setObjectName("txtciphertext")
        self.txtinformatic = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txtinformatic.setGeometry(QtCore.QRect(570, 160, 281, 71))
        self.txtinformatic.setObjectName("txtinformatic")
        self.txtsignature = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txtsignature.setGeometry(QtCore.QRect(580, 260, 281, 71))
        self.txtsignature.setObjectName("txtsignature")
        self.btnEncrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btnEncrypt.setGeometry(QtCore.QRect(90, 410, 75, 23))
        self.btnEncrypt.setObjectName("btnEncrypt")
        self.btnGenerateKeys = QtWidgets.QPushButton(self.centralwidget)
        self.btnGenerateKeys.setGeometry(QtCore.QRect(610, 70, 75, 23))
        self.btnGenerateKeys.setObjectName("btnGenerateKeys")
        self.btnDecrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btnDecrypt.setGeometry(QtCore.QRect(300, 410, 75, 23))
        self.btnDecrypt.setObjectName("btnDecrypt")
        self.btnSign = QtWidgets.QPushButton(self.centralwidget)
        self.btnSign.setGeometry(QtCore.QRect(540, 410, 75, 23))
        self.btnSign.setObjectName("btnSign")
        self.btnVerify = QtWidgets.QPushButton(self.centralwidget)
        self.btnVerify.setGeometry(QtCore.QRect(770, 410, 75, 23))
        self.btnVerify.setObjectName("btnVerify")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 170, 47, 13))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 290, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(440, 80, 47, 13))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(500, 190, 47, 13))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(500, 290, 47, 13))
        self.label_5.setObjectName("label_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 970, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnEncrypt.setText(_translate("MainWindow", "Encrypt"))
        self.btnGenerateKeys.setText(_translate("MainWindow", "Generate Keys"))
        self.btnDecrypt.setText(_translate("MainWindow", "Decrypt"))
        self.btnSign.setText(_translate("MainWindow", "Sign"))
        self.btnVerify.setText(_translate("MainWindow", "Verify"))
        self.label.setText(_translate("MainWindow", "Plaintext"))
        self.label_2.setText(_translate("MainWindow", "CipherText"))
        self.label_3.setText(_translate("MainWindow", "RSA"))
        self.label_4.setText(_translate("MainWindow", "Informatic"))
        self.label_5.setText(_translate("MainWindow", "Signature"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
